-- Run this once in PostgreSQL if Hibernate does not create the table automatically.
CREATE TABLE IF NOT EXISTS feedback (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feedback_submitted_at
ON feedback (submitted_at DESC);
